<?php

/*
+----------------------------------------------------+
|   e107 website system
|   e107_config.php
|
|   ©Steve Dunstan 2001-2002
|   http://e107.org
|   jalist@e107.org
|
|   Released under the terms and conditions of the
|   GNU General Public License (http://gnu.org).
+----------------------------------------------------+
This file has been generated by the installation script.
*/

$mySQLserver    = 'localhost';
$mySQLuser      = 'display-city_ru';
$mySQLpassword  = 'gfhjkmgjdsityyjqctrhtnyjcnb';
$mySQLdefaultdb = 'display-city';
$mySQLprefix    = 'e107_';

$ADMIN_DIRECTORY     = "admin/";
$FILES_DIRECTORY     = "files/";
$IMAGES_DIRECTORY    = "images/";
$THEMES_DIRECTORY    = "themes/";
$PLUGINS_DIRECTORY   = "plugins/";
$HANDLERS_DIRECTORY  = "handlers/";
$LANGUAGES_DIRECTORY = "languages/";
$HELP_DIRECTORY      = "docs/help/";
$DOWNLOADS_DIRECTORY = "files/downloads/";

?>
